### ISSUE TITLE
изменить стиль заголовков h1 и h2 

### ISSUE THREAD

**Issue by Smazhko** [Smazhko/git-adv-sem1#1]
работа в ветке develop
в файле style.css найти селектор заголовков и внести любые изменения (изменить цвет или размер шрифта, изменить отступы)

коммит называть по шаблону:
[номер задачи]-[никнейм]-[комментарий к коммиту]

после выполнения — создать pull request и перевести задачу обратно

**Comment by 555-F-a-r-id-555** [comment]
Задание принял @Smazhko

**Comment by 555-F-a-r-id-555** [comment]
Fast code - задание выполнил @Smazhko

**Comment by Smazhko** [comment]
@555-F-a-r-id-555  ветка задания влита в основную ветку проекта
