### ISSUE TITLE
изменить функцию function askAge()

### ISSUE THREAD

**Issue by Smazhko** [Smazhko/git-adv-sem1#2]
работа в ветке develop
в файле scripts.js изменить функцию function askAge(): поменять возрастные интервалы и изменить сообщения, выдаваемые при проверке возраста.

коммит называть по шаблону:
[номер задачи]-[никнейм]-[комментарий к коммиту]

после выполнения — создать pull request и перевести задачу обратно

**Comment by 555-F-a-r-id-555** [comment]
Задание принято @Smazhko

**Comment by 555-F-a-r-id-555** [comment]
Задание выполнил @Smazhko

**Comment by Smazhko** [comment]
задание принято. спасибо, @555-F-a-r-id-555
